# -*- coding: utf-8 -*-
"""Address Finder

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fweLHUyIlutbNNBk4Zd-mIBwAT47JSDU
"""

!pip install pyap

import pyap
test_address = """
nine on one what is your emerge antsy
some one just ran through my cool
what do you mean
some body aoh dove through the front of my cool
Lorem ipsum
1 white st westborough massachusetts
oh the car still there
any body injured
i have no idea i cant black throw get on the phone
ok into the back of the school

"""
addresses = pyap.parse(test_address, country='US')
for address in addresses:
    # shows found address
    print(address)
    # shows address parts
    print(address.as_dict())